### ISSUE TITLE
chore: add palindrome checker to main repo

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/CurriculumExpansion#608] opened 2024-09-17 23:14 UTC
We need to add the palindrome checker lab to main

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/build-a-palindrome-checker-project/build-a-palindrome-checker

Use the same ids

**Comment by ilenia-magoni** [comment] 2024-09-18 17:56
Isn't this a duplicate of https://github.com/freeCodeCamp/CurriculumExpansion/issues/512?

**Comment by jdwilkin4** [comment] 2024-09-18 21:22
oh yeah, I guess that was a duplicate.
I just approved the PR on main, so both issues will close when it gets merged

**Closed** 2024-09-24 14:54 UTC
Labels: Frontend Cert, Labs Team
