### ISSUE TITLE
Learn Debugging by Building a Dice Game

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/CurriculumExpansion#121] opened 2019-03-08 01:15 UTC

**Comment by S1ngS1ng** [comment] 2019-03-26 22:49
Hey Quincy, quick question here.
Personally, I consider debugging to be a way-of-thinking (methodology) or skill rather than a technology. Which means, we utilize debugging (as a handy tool) while programming, but we simply don't build a real-world project with "debugging", directly.
Though, if the initial idea is to utilize debugging during development, IMHO a video guide/session would be more helpful. Plus, there is no way we could verify the user's action within the debugger.

**Comment by QuincyLarson** [comment] 2019-03-27 03:41
@S1ngS1ng Yes - this is a good point. For this, it might be better to have a larger existing project and have them debug it with common mistakes present (off-by-one errors, etc) that they can spot and fix. Would you be interested in helping brainstorm such a project and build a prototype?

**Comment by S1ngS1ng** [comment] 2019-03-27 05:25
@QuincyLarson I'd definitely love to. Hopefully, I am able to bring up some valid points.

> it might be better to have a larger existing project

Totally, but I don't have any on my side.
freeCodeCamp is open source, but it might hard to get started for teaching debugging, IMO.

> common mistakes present

Here are the common mistakes/methodology I could come up:
1. Honestly, the most common mistakes (to me) is "Cannot read property 'x' of null/undefined"
    - This is easy to debug and fix, and easy to demonstrate
    - It could be combined with async process as well
2. The second most common mistakes (to me) is the typo 😂 
    - We shouldn't focus on this too much, yet it is nice to have. Most editor/IDE is bundled with the feature of variable availability check and spelling check
    - Typo, IMO, could be demonstrated via both misspelled variable and misspelled method
3. Use `debugger`
    1. To determine a logic error (no example given ATM 🤦‍♂️)
    2. To find the wrong parameter passed in when calling a method
    3. To find the issue caused by implicit type conversion (i.e., coercion)
    4. To determine the cause of an infinite loop
4. Use `console.trace()` to determine the root cause of an error
    - I consider it better to demonstrate with multiple files
    - Though, I can't come with a valid scenario other than third-party library

Adding to the above, `debugging` happens to CSS as well, IMO:
1. Demonstrate how default style works
    - e.g., Underline and color are both applied automatically on `anchor` tag
2. Demonstrate an "unexpected" result caused by specificity
    - (Here is a good reference: https://specifishity.com)
3. Demonstrate an "unexpected" result caused by cascading (i.e., overridden by the latter one)
    - It might be better to demonstrate w/ multiple files. The former one has a specific selector while the latter one has a more generic selector
4. I guess it might worth to mention margin collapse as well:
    - [MDN reference](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing)

Though, I haven't been working on CSS for a while. If you have any other suggestions, please let me know.

**Comment by QuincyLarson** [comment] 2019-03-27 16:28
@S1ngS1ng I'm CC'ing @HKuz to see what ideas she has about this. She created our current debugging curriculum.

**Comment by HKuz** [comment] 2019-03-27 23:21
Hi @S1ngS1ng - lot of good ideas coming off this thread! As @QuincyLarson noted, I helped write the current debugging challenges and can give you the general idea of what we were trying to do that go around if it helps.

The challenges focused on teaching campers the basic types of errors, how to catch them, and to treat debugging as a systematic approach. They admittedly didn't really touch on programmer tools like debuggers or editors that can help.

The three main areas were 1) syntax errors that prevent the code from even running (typos/spelling errors, un-closed brackets, etc.), 2) runtime errors where code fails to execute or misbehaves (infinite loops, off by one errors), and 3) semantic or logical errors when the code works but doesn't do what it's supposed to (like passing arguments to a function in the wrong order). 

I think for this section, the sky is the limit on the actual project that's used for the challenges. You have a lot of great ideas in your post above, then you can layer in any of the existing challenge ideas if you'd like (I've copied a list of the titles below for your reference). I think the key here is to point out the most common mistakes and have them practice fixing them, so they have an idea of where to start looking when things go wrong (my personal nemesis when I started was the assignment vs equality operator mistake).

Here's the list of the challenges from the existing curriculum for your reference:

- Use the JavaScript Console to Check the Value of a Variable
- Use `typeof` to Check the Type of a Variable
- Catch Misspelled Variable and Function Names
- Catch Unclosed Parentheses, Brackets, Braces and Quotes
- Catch Mixed Usage of Single and Double Quotes
- Catch Use of Assignment Operator Instead of Equality Operator
- Catch Missing Open and Closing Parenthesis After a Function Call
- Catch Arguments Passed in the Wrong Order when Calling a Function
- Catch "Off By One" Errors When Using Indexing
- Use Caution When Reinitializing Variables Inside a Loop
- Prevent Infinite Loops with a Valid Terminal Condition

Let me know if you have any questions!

**Comment by QuincyLarson** [comment] 2019-03-30 02:06
@HKuz Thanks for sharing these details. Your debugging curriculum has been extremely useful, and it sounds like there is so much more we can teach with this as well. 

@S1ngS1ng What are your thoughts on this?

**Comment by S1ngS1ng** [comment] 2019-03-30 05:23
@HKuz Thanks for your sharing, that has been really helpful.

@QuincyLarson Sorry, I read through HKuz's comment above, but haven't got a chance for some brain-storming on this.
I'll finish the Poker Game ASAP, and come back to this in a few days. I think it might take me a couple of days to have a viable code base for this, which covers as much use cases as mentioned above.

**Comment by scissorsneedfoodtoo** [comment] 2019-04-12 06:34
@S1ngS1ng, just wanted to check in and see if you've started working on this already. If not, I think it's best that we open this project up to someone else while you finish the poker game. It'll take some time to break that project down!

**Comment by S1ngS1ng** [comment] 2019-04-12 07:01
@scissorsneedfoodtoo I've been thinking about it. Hopefully, I could get write some summaries by the end of this weekend. Though, probably not a workable project AFAIC. 😞 
But yeah, if anyone else is interested in working on this, feel free to take it over.

**Comment by scissorsneedfoodtoo** [comment] 2019-04-12 08:41
@S1ngS1ng, no worries! Any sort of summary would be greatly appreciated. I'll post a "help wanted" label for now, but you're welcome to pick it up again later down the road.

**Comment by beaucarnes** [comment] 2019-05-21 14:58
I'm working on a simple project that can be "debugged" for this challenge.

**Comment by beaucarnes** [comment] 2019-05-21 19:08
I created this simple "Dice Game" program. I'm going to add some bugs, and then create challenges / instructions to fix the bugs.

https://codepen.io/beaucarnes/pen/YbEpZM

**Comment by scissorsneedfoodtoo** [comment] 2019-05-22 09:02
@beaucarnes, this looks great! Seems like a really good project to teach the concepts that were discussed above without being overwhelming. I'll go ahead and change the project title here and over on the forum.

**Comment by GedalyaBlau** [comment] 2022-04-05 11:10
hi... this project is both "not started" in front three projects, and also "ready to code project tests" in back seven projects... so which is it?

**Comment by scissorsneedfoodtoo** [comment] 2022-04-05 12:55
Thanks for pointing that out, @GedalyaBlau. I've removed it from that project board.

We've largely moved over to a spreadsheet for curriculum planning. The spreadsheet makes it easier to see the big picture, sequence the projects, and track which concepts are taught / reviewed across multiple projects.

Here's a link if you're interested in our progress: https://docs.google.com/spreadsheets/d/1KXEJvgnAziiePMp2Ovf_ssDqCFFWYuycXWBNp91k3qM

**Comment by GedalyaBlau** [comment] 2022-04-05 13:20
thank you!

**Closed** 2022-07-26 04:19 UTC
